name: isce3_rtc
channels:
  - conda-forge
dependencies:
  - python>=3.9,<3.10
  - cmake>=3.18
  - eigen>=3.3
  - fftw>=3.3
  - gdal>=3.0
  - gmock>=1.10
  - gtest>=1.10
  - h5py>=3.0
  - hdf5>=1.10.2
  - libgcc-ng
  - libstdcxx-ng
  - numpy>=1.20
  - pybind11>=2.5
  - pyre>=1.11.2
  - pytest
  - cython
  - ruamel.yaml
  - scipy!=1.10.0
  - setuptools
  - shapely
  - yamale
  - backoff
  - isce3=0.9.0
