name: isce3_rtc
channels:
  - conda-forge
dependencies:
  - python>=3.9,<3.10
  - cmake
  - eigen
  - fftw
  - gdal
  - gmock
  - gtest
  - h5py
  - hdf5>=1.10.2
  - libgcc-ng
  - libstdcxx-ng
  - numpy
  - pybind11
  - pyre
  - pytest
  - cython
  - ruamel.yaml
  - scipy
  - setuptools
  - shapely
  - yamale
  - backoff
  - isce3=0.9.0
