version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:current
    resource_class: medium
    steps:
      - checkout
      - run:
          name: "Build RTC docker image"
          command: |
            docker build . -f docker/Dockerfile

workflows:
  build-workflow:
    jobs:
      - build
