name: rtc_s1_sas_final
channels:
  - conda-forge
dependencies:
  - python>=3.9,<3.10
  - gdal>=3.0
  - s1reader>=0.2.1
  - numpy>=1.20
  - pybind11>=2.5
  - pyre>=1.11.2
  
  - scipy!=1.10.0
  - isce3>=0.14.0